//
//  CityDetailInteractorTests.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 15.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest

class CityDetailInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CityDetailInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupCityDetailInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCityDetailInteractor() {
        sut = CityDetailInteractor()
    }
    
    // MARK: Test doubles
    
    class CityDetailPresentationLogicSpy: CityDetailPresentationLogic {
        var presentCityDetailCalled = false
        
        func presentCityDetail(with viewModel: CityDetail.MapViewModel?) {
            presentCityDetailCalled = true
        }
    }
    
    // MARK: Tests
    
    func testDoSomething() {
        // Given
        let spy = CityDetailPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        
        // Then
    }
}
