//
//  CityListPresenter.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 13.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityListPresentationLogic {
    func presentCityList(cityItemList: [CityList.CityItemModel])
}

final class CityListPresenter: CityListPresentationLogic {
    
  weak var viewController: CityListDisplayLogic?

    func presentCityList(cityItemList: [CityList.CityItemModel]) {
        let sortedItemList = cityItemList.sorted {
            guard let first = $0.name else {
                return false
            }
            guard let second = $1.name else {
                return true
            }

            return first.localizedCaseInsensitiveCompare(second) == ComparisonResult.orderedAscending
        }
        
        viewController?.displayCityList(cityItemList: sortedItemList)
    }
}
