//
//  CityListRouter.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 13.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityListRoutingLogic {
    func routeToCityDetail(viewModel: CityDetail.MapViewModel)
}

protocol CityListDataPassing {
    var dataStore: CityListDataStore? { get }
}

final class CityListRouter: NSObject, CityListRoutingLogic, CityListDataPassing {
    weak var viewController: CityListViewController?
    var dataStore: CityListDataStore?
    
    
    func routeToCityDetail(viewModel: CityDetail.MapViewModel) {
        let storyboard = UIStoryboard(name: "CityDetail", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "CityDetail") as! CityDetailViewController
        var destinationDS = destinationVC.router!.dataStore!

        passDataToCityDetail(viewModel: viewModel, source: dataStore!, destination: &destinationDS)
        navigateToCityDetail(source: viewController!, destination: destinationVC)
    }
    
    //   MARK: Navigation
    
    func navigateToCityDetail(source: CityListViewController, destination: CityDetailViewController) {
        source.show(destination, sender: nil)
    }
    
    //   MARK: Passing data
    
    func passDataToCityDetail(viewModel: CityDetail.MapViewModel, source: CityListDataStore, destination: inout CityDetailDataStore) {
        destination.mapViewModel = viewModel
    }
}
