//
//  CityListRouter.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 13.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol CityListRoutingLogic {
}

protocol CityListDataPassing {
  var dataStore: CityListDataStore? { get }
}

final class CityListRouter: NSObject, CityListRoutingLogic, CityListDataPassing {
  weak var viewController: CityListViewController?
  var dataStore: CityListDataStore?
  
}
