//
//  CityListInteractor.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 13.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityListBusinessLogic {
    func getCityList()
}

protocol CityListDataStore {
    //var name: String { get set }
}

final class CityListInteractor: CityListBusinessLogic, CityListDataStore {
    var presenter: CityListPresentationLogic? = nil
    
    var viewModel: CityList.CityItemModel?
    
    func getCityList() {
        
        if let url = Bundle.main.url(forResource: "cities", withExtension: "json") {
            do {
                let jsonData = try Data(contentsOf: url)
                presenter?.presentCityList(cityItemList: parse(jsonData: jsonData))
            }
            catch {
                print(error)
            }
        }
    }
    
    private func parse(jsonData: Data) -> [CityList.CityItemModel] {
        do {
            debugPrint("decoded successfully")
            return  try JSONDecoder().decode([CityList.CityItemModel].self, from: jsonData)
        } catch {
            print("error: \(error)")
            return []
        }
    }
}
