//
//  CityListViewController.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 13.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol CityListDisplayLogic: AnyObject {
    func displayCityList(cityItemList: [CityList.CityItemModel])
}

final class CityListViewController: UIViewController, CityListDisplayLogic {
    
    var interactor: CityListBusinessLogic?
    var router: (NSObjectProtocol & CityListRoutingLogic & CityListDataPassing)?
    
    @IBOutlet private var tableView: UITableView!
    private let searchController = UISearchController(searchResultsController: nil)
    private var cityModelList: [CityList.CityItemModel]? = []
    private var filteredCities: [CityList.CityItemModel] = []
    
    var isSearchBarEmpty: Bool {
        return searchController.searchBar.text?.isEmpty ?? true
    }
    
    var isFiltering: Bool {
        return searchController.isActive && !isSearchBarEmpty
    }
    
    // MARK: Object lifecycle
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    // MARK: Setup
    
    private func setup() {
        let viewController = self
        let interactor = CityListInteractor()
        let presenter = CityListPresenter()
        let router = CityListRouter()
        viewController.interactor = interactor
        viewController.router = router
        interactor.presenter = presenter
        presenter.viewController = viewController
        router.viewController = viewController
        router.dataStore = interactor
    }
    
    // MARK: View lifecycle
    
    override func viewDidLoad() {
        super.viewDidLoad()
        navigationItem.backBarButtonItem = UIBarButtonItem(title: "", style: .plain, target: nil, action: nil)
        
        registerTableView()
        setSearchViewController()
        
        interactor?.getCityList()
    }
    
    private func registerTableView() {
        tableView.delegate = self
        tableView.dataSource = self
        
        tableView.register(CustomTableViewCell.self, forCellReuseIdentifier: "CustomTableViewCell")
    }
    
    private func setSearchViewController() {
        searchController.searchResultsUpdater = self
        searchController.obscuresBackgroundDuringPresentation = false
        searchController.searchBar.placeholder = "Cities"
        
        navigationItem.searchController = searchController
        navigationItem.hidesSearchBarWhenScrolling = false
        navigationItem.accessibilityScroll(.down)
        definesPresentationContext = true
    }
    
    private func filterContentForSearchText(_ searchText: String,
                                            category: CityList.CityItemModel? = nil) {
        
        filteredCities = (cityModelList?.filter({ item in
            (item.name!.lowercased().contains(searchText.lowercased()))
        }))!
    }
    
    func displayCityList(cityItemList: [CityList.CityItemModel]) {
        cityModelList = cityItemList
    }
}

extension CityListViewController: UITableViewDelegate, UITableViewDataSource {
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        if isFiltering {
            return filteredCities.count
        }
        return cityModelList?.count ?? 0
    }
    // TODO: Refactor etmeyi unutma metodları ortaklastır
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        if let cell = tableView.dequeueReusableCell(withIdentifier: "CustomTableViewCell") as? CustomTableViewCell {
            let simpleItemView = SimpleItemView(frame: CGRect(x: 0, y: 0, width: UIScreen.main.bounds.width, height: 70))

            if isFiltering {
                let simpleItemViewModel = filteredCities.map { item -> SimpleItemViewModel in
                    let title: String = item.name! + ", " + item.countryName!
                    let subTitle: String = String((item.coordinate?.longitude)!) + ", " + String((item.coordinate?.latitude)!)

                    return SimpleItemViewModel(id: item.id,
                                               title: title,
                                               subTitle: subTitle)
                }
                simpleItemView.viewModel = simpleItemViewModel[indexPath.row]
                cell.component = simpleItemView
                return cell

            } else {
                let simpleItemViewModel = cityModelList!.map { item -> SimpleItemViewModel in
                    let title: String = item.name! + ", " + item.countryName!
                    let subTitle: String = String((item.coordinate?.longitude)!) + ", " + String((item.coordinate?.latitude)!)

                    return SimpleItemViewModel(id: item.id,
                                               title: title,
                                               subTitle: subTitle)
                }
                simpleItemView.viewModel = simpleItemViewModel[indexPath.row]
                cell.component = simpleItemView
                return cell            }
        }
        
        return UITableViewCell()
//        if isFiltering {
//            let cell = tableView.dequeueReusableCell(withIdentifier: "deneme")
//            cell?.textLabel?.text = filteredCities[indexPath.row].name
//            return cell!
//        }
//
//        let cell = tableView.dequeueReusableCell(withIdentifier: "deneme")
//        cell?.textLabel?.text = cityModelList![indexPath.row].name
//        return cell!
    }
    
    func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        if isFiltering {
            let viewModel = filteredCities.map { item in
                return CityDetail.MapViewModel(title: item.name ?? "City",
                                               coordinate: CLLocationCoordinate2D(latitude: item.coordinate?.latitude ?? 51.5549,
                                                                                  longitude: item.coordinate?.longitude ?? -0.108436),
                                               info: "City Location")
            }
            router?.routeToCityDetail(viewModel: viewModel[indexPath.row])
        } else {
            if let cityModelList = cityModelList {
                let viewModel = cityModelList.map { item in
                    return CityDetail.MapViewModel(title: item.name ?? "City",
                                                   coordinate: CLLocationCoordinate2D(latitude: item.coordinate?.latitude ?? 51.5549,
                                                                                      longitude: item.coordinate?.longitude ?? -0.108436),
                                                   info: "City Location")
                }
                router?.routeToCityDetail(viewModel: viewModel[indexPath.row])
            }
        }
    }
    
    
}

extension CityListViewController: UISearchResultsUpdating {
    func updateSearchResults(for searchController: UISearchController) {
        let searchBar = searchController.searchBar
        filterContentForSearchText(searchBar.text!)
        tableView.reloadData()
    }
}
