//
//  CityDetailInteractor.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 13.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CityDetailBusinessLogic {
    func getMapViewModel()
}

protocol CityDetailDataStore {
    var mapViewModel: CityDetail.MapViewModel? { get set }
}

final class CityDetailInteractor: CityDetailBusinessLogic, CityDetailDataStore {

    var presenter: CityDetailPresentationLogic?
    var mapViewModel: CityDetail.MapViewModel?
    
    func getMapViewModel() {
        presenter?.presentCityDetail(with: mapViewModel)
    }
}
