//
//  CityListPresenterTests.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 15.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import SearchingCities
import XCTest

class CityListPresenterTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CityListPresenter!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupCityListPresenter()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCityListPresenter() {
        sut = CityListPresenter()
    }
    
    // MARK: Test doubles
    
    class CityListDisplayLogicSpy: CityListDisplayLogic {
        var displayCityListCalled = false
        
        func displayCityList(simpleItemModelList: [SimpleItemViewModel], cityItemList: [CityList.CityItemModel], contentViewModel: ContentViewModel?) {
            displayCityListCalled = true
        }
    }
    
    // MARK: Tests
    
    func testPresentSomething() {
        // Given
        let spy = CityListDisplayLogicSpy()
        sut.viewController = spy
        
        // When
        
        // Then
    }
}
