//
//  CityListViewControllerTests.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 15.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest

class CityListViewControllerTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CityListViewController!
    var window: UIWindow!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        window = UIWindow()
        setupCityListViewController()
    }
    
    override func tearDown() {
        window = nil
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCityListViewController() {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "CityList", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "CityListViewController") as? CityListViewController
    }
    
    func loadView() {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: Test doubles
    
    class CityListBusinessLogicSpy: CityListBusinessLogic {
        var getCityListCalled = false
        
        func getCityList() {
            getCityListCalled = true
        }
    }
    
    // MARK: Tests
}
