//
//  CityListInteractorTests.swift
//  SearchingCities
//
//  Created by Yeşim Daşdemir on 15.05.2021.
//  Copyright (c) 2021 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import XCTest

class CityListInteractorTests: XCTestCase {
    // MARK: Subject under test
    
    var sut: CityListInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp() {
        super.setUp()
        setupCityListInteractor()
    }
    
    override func tearDown() {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupCityListInteractor() {
        sut = CityListInteractor()
    }
    
    // MARK: Test doubles
    
    class CityListPresentationLogicSpy: CityListPresentationLogic {
        var presentCityListCalled = false
        
        func presentCityList(cityItemList: [CityList.CityItemModel]) {
            presentCityListCalled = true
        }
    }
    
    // MARK: Tests
    
    func testDoSomething() {
        // Given
        let spy = CityListPresentationLogicSpy()
        sut.presenter = spy
        
        // When
        
        // Then
    }
}
